name: Deploy to Tencent Cloud

on:
  push:
    branches:
      - main
      - debug

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 获取 pnpm store directory
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # 设置 pnpm cache
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # 安装依赖
      - name: Install Dependencies
        run: pnpm install

      # 构建 VuePress 站点
      - name: Build VuePress Site
        run: pnpm run build

      # Determine remote path based on branch
      - name: Determine Remote Path
        id: remote_path
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH_NAME" == "debug" ]]; then
            echo "remote_path=/home/emptydust/website/insuep/debug" >> $GITHUB_OUTPUT
          else
            echo "remote_path=/home/emptydust/website/insuep/repo" >> $GITHUB_OUTPUT
          fi
          echo "Deploying to $BRANCH_NAME"

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: "emptydust" #ssh user name
          server: "${{ secrets.SERVER_IP }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./docs/.vuepress/dist"
          remote_path: ${{ steps.remote_path.outputs.remote_path }}
